In [18]:
def inventory_report(product: str):
    import pandas as pd
    from inventory_control.db_models import engine
    
    df = pd.read_sql_query(f"SELECT * FROM productlist WHERE product_name = '{product}'", engine)

    for index in df.index:
        if index > 0:
            current_index = index
            prior_index = index - 1

            prior_units_available = df.loc[df.index == prior_index, "units_available"].item()
            current_units_available = df.loc[df.index == current_index, "quantity"].item()

            new_units_available = int(current_units_available) + int(prior_units_available)

            prior_inventory_value = df.loc[df.index == prior_index, "inventory_value"].item()
            current_total = df.loc[df.index == current_index, "total"].item()

            new_inventory_value = float(current_total) + float(prior_inventory_value)

            new_unit_cost = new_inventory_value / new_units_available

            df.loc[df.index == current_index, "units_available"] = new_units_available
            df.loc[df.index == current_index, "inventory_value"] = round(new_inventory_value,2)
            df.loc[df.index == current_index, "unit_cost"] = round(new_unit_cost,2)
        else:
            df.loc[df.index == 0, "units_available"] = int(df.loc[df.index == 0, "quantity"].item())
            df.loc[df.index == 0, "inventory_value"] = float(df.loc[df.index == 0, "total"].item())
            df.loc[df.index == 0, "unit_cost"] = float(df.loc[df.index == 0, "price"].item())

    return df

In [19]:
df = inventory_report("Product A")
df

,id_operation,product_name,quantity,price,total,operation,related_id,units_available,inventory_value,unit_cost
0,2,Product A,43,16.45,707.35,Purchase,None,43.0,707.35,16.45
1,4,Product A,45,16.59,746.55,Purchase,None,88.0,1453.90,16.52
2,5,Product A,32,10.70,342.40,Purchase,None,120.0,1796.30,14.97
3,7,Product A,19,15.80,300.20,Purchase,None,139.0,2096.50,15.08
4,8,Product A,12,16.41,196.92,Purchase,None,151.0,2293.42,15.19
5,15,Product A,48,16.26,780.48,Purchase,None,199.0,3073.90,15.45
6,18,Product A,30,17.23,516.90,Purchase,None,229.0,3590.80,15.68
7,19,Product A,42,13.76,577.92,Purchase,None,271.0,4168.72,15.38

In [20]:
data2 = df.loc[df["operation"] == "Purchase"]
data2

,id_operation,product_name,quantity,price,total,operation,related_id,units_available,inventory_value,unit_cost
0,2,Product A,43,16.45,707.35,Purchase,None,43.0,707.35,16.45
1,4,Product A,45,16.59,746.55,Purchase,None,88.0,1453.90,16.52
2,5,Product A,32,10.70,342.40,Purchase,None,120.0,1796.30,14.97
3,7,Product A,19,15.80,300.20,Purchase,None,139.0,2096.50,15.08
4,8,Product A,12,16.41,196.92,Purchase,None,151.0,2293.42,15.19
5,15,Product A,48,16.26,780.48,Purchase,None,199.0,3073.90,15.45
6,18,Product A,30,17.23,516.90,Purchase,None,229.0,3590.80,15.68
7,19,Product A,42,13.76,577.92,Purchase,None,271.0,4168.72,15.38

In [21]:
data2.loc[data2["id_operation"] == 2, "price"].item()

16.45